### ISSUE TITLE
Support for Zone Control

### ISSUE THREAD

**Issue by AaronMountford** [scottyphillips/mitsubishi_hass#6]
Hi Scotty

Loving this, as I also could not get Jethro's docker implementation to work (doesn't detect my system/echonetlite).

Would you please be able to add support for Zone control?  My home has three zones that I'd like to be able to control independently (as is currently possible through the mobile app).

Thanks
Aaron

**Comment by scottyphillips** [comment]
According to the ECHONET spec sheet, the only thing Zone control related seems to be present in the 'Floor Heater' class, rather than the 'Home Air Conditioner' class. 

I have a third party zone controller (which in hindsight is a PITA) so its not something I myself have wanted or been able to implement. I have never played with any other ECHONET classes so its nothing something I can really help with much directly. 

You may want to do some investigation at your end if you are comfortable enough with Python using the ECHONET library i coded as part of this project. Install the library using PIP and try to run a 'Discover' from CLI and see what classes you get. If it is just 'Home Air Conditioner' then we are out of luck. 

I am pretty sure the 'Climate' class in HA has no support for Zones so it would need to be a seperate implementation like a switch per zone or similar. 

(https://github.com/scottyphillips/mitsubishi_echonet)

https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_L_en/Appendix_Release_L_E.pdf

**Comment by stuarts0011** [comment]
Hi Scotty,
I am having trouble getting a sensible response from the 'mit.discover' command. I used:

import mitsubishi_echonet as mit
mit.discover

Could you confirm the precise syntax I should use to poll for any other nodes?

**Comment by scottyphillips** [comment]
Are you trying to discover other Air conditioners?

 

aircons = mit.discover('Home air conditioner')

 

it should return a list of any HomeAirConditioner objects that it discovers. It uses a multicast address 224.0.23.0 and port 3610 to find them.

 

Scott

**Comment by stuarts0011** [comment]
> Are you trying to discover other Air conditioners? aircons = mit.discover('Home air conditioner') it should return a list of any HomeAirConditioner objects that it discovers. It uses a multicast address 224.0.23.0 and port 3610 to find them. Scott From: stuarts0011 <notifications@github.com> Reply-To: scottyphillips/mitsubishi_hass <reply@reply.github.com> Date: Sunday, 31 May 2020 at 1:17 pm To: scottyphillips/mitsubishi_hass <mitsubishi_hass@noreply.github.com> Cc: Scott Phillips <scotty.phillips@hotmail.com>, State change <state_change@noreply.github.com> Subject: Re: [scottyphillips/mitsubishi_hass] Support for Zone Control (#6) Hi Scotty, I am having trouble getting a sensible response from the 'mit.discover' command. I used: import mitsubishi_echonet as mit mit.discover Could you confirm the precise syntax I should use to poll for any other nodes? — You are receiving this because you modified the open/close state. Reply to this email directly, view it on GitHub, or unsubscribe.

I'm trying to discover something else that may have been implemented as the zone controller. But I do not get any response from the command you mention. 

print(aircons)
[]

**Comment by scottyphillips** [comment]
Okay so I’ve pushed an update to the git repo under ‘master’ (I am assuming you have pulled the Mitsubishi_echonet code and not running it via PIP)

 

Now if you run ./example.py that is in the repo it should return any ECHONET node objects that it finds. 

 

Code below:

#!/usr/bin/env python3

import mitsubishi_echonet as mit

import time

 

echonet_objects = False

# Discover HVAC Echonet objects

while echonet_objects == False:

    print("Discovering Anything..")

    echonet_objects = mit.discover()

 

for node in echonet_objects:

   print("ECHONET node {} available Get properties:".format(node.netif))

   #print(aircon.netif)

   print(node.fetchGetProperties())

 

   print("ECHONET node {} available Set properties:".format(node.netif))

   print(node.fetchSetProperties())

 

Scott

**Comment by stuarts0011** [comment]
Thanks. Its still not returning anything. Must be something to do with the multicast polling. Can it be pointed at the actual ip address of the wifi?

**Comment by scottyphillips** [comment]
Sorry if you want to get your zones to work go nuts but you are going to have to figure it out yourself. I’ve already said that the HomeAirConditioner class does not support zones.

**Comment by stuarts0011** [comment]
[Does OIC mean Oh I See?  ]

Yes. Thanks for your work and help anyway.

**Comment by scottyphillips** [comment]
https://github.com/zacharyrs/ha-melview

Maybe reverse engineer the cloud based implementation by Zacharys and implement a switch for home assistant.

**Comment by AaronMountford** [comment]
I think the code you're looking for is 

import mitsubishi_echonet as mit
aircon = mit.HomeAirConditioner('192.168.60.13')
print(aircon.__dict__)

(obviously substitute your own AC's IP) 

I've gotten as far as trying to read the Echonet lite spec, but it's pretty dry going :)   Also having to learn python from scratch at the same time isn't helping.   Let me know if you want to colaborate on getting the zones working.  I imagine they'll end up as a series of switches in HA unless we can convince someone to add them to the HA hvac class.


> Hi Scotty,
> I am having trouble getting a sensible response from the 'mit.discover' command. I used:
> 
> import mitsubishi_echonet as mit
> mit.discover
> 
> Could you confirm the precise syntax I should use to poll for any other nodes?

**Comment by abowen** [comment]
I know this issue is closed, but just adding a link to discussion here in case anyone like me in future comes along and looking into zones

https://community.home-assistant.io/t/mitsubishi-aircon/37454/151
